# Generated by Django 2.0 on 2019-10-31 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=32, unique=True)),
                ('type', models.CharField(max_length=32)),
                ('passwd', models.CharField(max_length=32)),
                ('server', models.CharField(max_length=32)),
                ('server_port_number', models.CharField(max_length=32)),
            ],
        ),
    ]
